# Generated by Django 5.2.5 on 2025-11-24 20:17

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify
import itertools

# --- FUNÇÃO DE CORREÇÃO PARA PREENCHER SLUGS ÚNICOS ---
def set_unique_slugs(apps, schema_editor):
    """
    Popula o campo 'slug' para todos os projetos existentes,
    garantindo que cada slug seja único.
    """
    Project = apps.get_model('core', 'Project')
    
    for project in Project.objects.all():
        # Cria o slug a partir do título
        base_slug = slugify(project.title)
        unique_slug = base_slug
        num = 1
        
        # Garante a unicidade: se o slug já existir (excluindo o próprio objeto)
        # adiciona um número sequencial (ex: projeto-a-1, projeto-a-2)
        while Project.objects.exclude(pk=project.pk).filter(slug=unique_slug).exists():
            unique_slug = f'{base_slug}-{num}'
            num += 1
            
        project.slug = unique_slug
        # Usa .save() para persistir a mudança de dados no banco
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        # Preserva todas as alterações de opções e Adiciona novos campos
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destaque na Página'),
        ),
        
        # --- CORREÇÃO DO SLUG: 3 PASSOS ---
        # 1. Adiciona o campo SLUG temporariamente (permite NULL, SEM unique=True)
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=50, blank=True, null=True, verbose_name='URL Amigável'),
        ),
        
        # 2. Roda a função para preencher os slugs de forma única nos dados existentes
        migrations.RunPython(set_unique_slugs, migrations.RunPython.noop),
        
        # 3. Altera o campo SLUG para impor a restrição UNIQUE e NOT NULL
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, max_length=50, blank=False, null=False, verbose_name='URL Amigável'),
        ),
        # ----------------------------------

        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status de Publicação'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_to_join',
            field=models.URLField(blank=True, help_text='Link externo para o projeto (ex: GitHub, site)', null=True, verbose_name='Link de Participação'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]