# Generated by Django 5.2.5 on 2025-11-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options_project_featured_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL Amigável'),
        ),
    ]
