# Generated by Django 5.2.5 on 2025-11-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_options_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_to_join',
            field=models.URLField(blank=True, help_text='Link externo para inscrição', null=True),
        ),
    ]
