# Generated by Django 5.2.5 on 2025-12-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_created_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
