# Generated by Django 5.2.5 on 2025-12-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallerygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='read_time',
        ),
    ]
